resources:
- hemihatchlings-api-deployment.yaml
- hemihatchlings-api-service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hemilabs/hemihatchlings-api:1.0.0
  newName: hemilabs/hemihatchlings-api
  newTag: testnet-v1.0.4
namespace: hemihatchlings-staging
