apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
 - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: hemihatchlings-web-ingress
   path: staging-patch.yaml