name: '[hemihatchlings] dockerhub web push'

on:
  push:
    tags:
      - 'v*'

jobs:
  dockerhubpush-VKEdeploy:
    env:
      namespace: hemihatchlings

    name: '[hemihatchlings] dockerhub web push'
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push hemihatchlings-web
        uses: docker/build-push-action@v3
        with:
          tags: hemilabs/hemihatchlings-web:${{ steps.vars.outputs.tag }}
          context: "{{defaultContext}}"
          file: "Dockerfile.web"
          push: true

      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install kubectl
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.VKE_TEST_KUBECONFIG }}
          
      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2
    
      - name: Configure K8s Cluster Access for VKE
        env:
          VKE_TEST_KUBECONFIG: ${{ secrets.VKE_TEST_KUBECONFIG }}
        run: |
          echo $VKE_TEST_KUBECONFIG > ./kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
  
      - name: Create K8s Secrets
        run: |
          if kubectl get configmap hemihatchlings-config --namespace=${{ env.namespace }}; then
            echo "hemihatchlings-config already exists"
          else
            echo "Creating hemihatchlings-config"
            kubectl create configmap hemihatchlings-config \
            --from-literal=VITE_API_URL=${{ secrets.VITE_API_URL }} \
            --from-literal=VITE_CHAIN_ID=${{ secrets.VITE_CHAIN_ID }} \
            --from-literal=VITE_CHAIN_NAME=${{ secrets.VITE_CHAIN_NAME }} \
            --from-literal=VITE_CHAIN_NETWORK=${{ secrets.VITE_CHAIN_NETWORK }} \
            --from-literal=VITE_CHAIN_RPC_URL=${{ secrets.VITE_CHAIN_RPC_URL }} \
            --from-literal=VITE_CHAIN_BLOCK_EXPLORER_URL=${{ secrets.VITE_CHAIN_BLOCK_EXPLORER_URL }} \
            --from-literal=VITE_CHAIN_CURRENCY_NAME=${{ secrets.VITE_CHAIN_CURRENCY_NAME }} \
            --from-literal=VITE_CHAIN_CURRENCY_SYMBOL=${{ secrets.VITE_CHAIN_CURRENCY_SYMBOL }} \
            --from-literal=VITE_FIRE_SMART_CONTRACT_ADDRESS=${{ secrets.VITE_FIRE_SMART_CONTRACT_ADDRESS }} \
            --from-literal=VITE_WATER_SMART_CONTRACT_ADDRESS=${{ secrets.VITE_WATER_SMART_CONTRACT_ADDRESS }} \
            --from-literal=VITE_GRASS_SMART_CONTRACT_ADDRESS=${{ secrets.VITE_GRASS_SMART_CONTRACT_ADDRESS }} \
            --from-literal=PORT=${{ secrets.PORT }} \
            --from-literal=RPC_URL=${{ secrets.RPC_URL }} \
            --namespace=${{ env.namespace }}
          fi
          echo "Checking Dockerhub Secret"
  
    
      - name: Dockerhub Secrets
        run: |
          if kubectl get secret dockerhub-secret --namespace=${{ env.namespace }}; then
            echo "Dockerhub Secret already exists"
          else
            echo "Creating Dockerhub Secret"
            kubectl create secret docker-registry dockerhub-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --docker-email=${{ secrets.DOCKER_EMAIL }} \
            --namespace=${{ env.namespace }}
          fi

      - name: Update Image Tag in deployment
        run: |
              kustomize edit set image hemilabs/hemihatchlings-web:latest=hemilabs/hemihatchlings-web:${{ steps.vars.outputs.tag }}
              kustomize edit set namespace ${{ env.namespace }}
        working-directory: ./infrastructure/kustomize_web

      - name: Checking Kustomize
        run: |
          kustomize build ./infrastructure/kustomize_api
          kubectl get all --namespace=${{ env.namespace }}
      
      - name: Deploy to VKE
        run: kubectl apply -k ./infrastructure/kustomize_web
