name: '[hemihatchlings] dockerhub api push'

on:
  push:
    tags:
      - 'v*'

jobs:
  dockerhubpush-VKEdeploy:
    env:
      namespace: hemihatchlings

    name: '[hemihatchlings] dockerhub api push'
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push hemihatchlings-api
        uses: docker/build-push-action@v3
        with:
          tags: hemilabs/hemihatchlings-api:${{ steps.vars.outputs.tag }}
          context: "{{defaultContext}}"
          file: "Dockerfile.api"
          push: true

      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install kubectl
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.VKE_TEST_KUBECONFIG }}
        
      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2
  
      - name: Configure K8s Cluster Access for VKE
        env:
          VKE_TEST_KUBECONFIG: ${{ secrets.VKE_TEST_KUBECONFIG }}
        run: |
          echo $VKE_TEST_KUBECONFIG > ./kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
  
      - name: Dockerhub Secrets
        run: |
          if kubectl get secret dockerhub-secret --namespace=${{ env.namespace }}; then
            echo "Dockerhub Secret already exists"
          else
            echo "Creating Dockerhub Secret"
            kubectl create secret docker-registry dockerhub-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --docker-email=${{ secrets.DOCKER_EMAIL }} \
            --namespace=${{ env.namespace }}
          fi
  
      - name: Update Image Tag in deployment
        run: |
              kustomize edit set image hemilabs/hemihatchlings-api:latest=hemilabs/hemihatchlings-api:${{ steps.vars.outputs.tag }}
              kustomize edit set namespace ${{ env.namespace }}
        working-directory: ./infrastructure/kustomize_api

      - name: Checking Kustomize
        run: |
          kustomize build ./infrastructure/kustomize_api
          kubectl get all --namespace=${{ env.namespace }}
    
      - name: Deploy to VKE
        run: kubectl apply -k ./infrastructure/kustomize_api
