name: '[hemihatchlings] dockerhub web push'

on:
  push:
    tags:
      - 'mainnet-v*'
      - 'testnet-v*'

jobs:
  dockerhubpush-VKEdeploy:

    name: '[hemihatchlings] dockerhub web push'
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: vars
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "tag=${TAG_NAME}" >> $GITHUB_ENV
          if [[ $TAG_NAME == "mainnet-v"* ]]; then
            echo "DOCKERFILE=Dockerfile.web.mainnet" >> $GITHUB_ENV
            echo "namespace=hemihatchlings" >> $GITHUB_ENV
            echo "REPO=hemilabs/hemihatchlings-web" >> $GITHUB_ENV
            echo "INFRA=infrastructure/kustomize_web" >> $GITHUB_ENV
          elif [[ $TAG_NAME == "testnet-v"* ]]; then
            echo "DOCKERFILE=Dockerfile.web.testnet" >> $GITHUB_ENV
            echo "namespace=hemihatchlings-test" >> $GITHUB_ENV
            echo "REPO=hemilabs/hemihatchlings-test" >> $GITHUB_ENV
            echo "INFRA=infrastructure/kustomize_web_test" >> $GITHUB_ENV
          fi

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push hemihatchlings-web
        uses: docker/build-push-action@v3
        with:
          tags: ${{ env.REPO }}:${{ env.tag }}
          context: "{{defaultContext}}"
          file: ${{ env.DOCKERFILE }}
          push: true

      - name: Build and Push hemihatchlings-api
        uses: docker/build-push-action@v3
        with:
          tags: hemilabs/hemihatchlings-api:${{ env.tag }}
          context: "{{defaultContext}}"
          file: "Dockerfile.api"
          push: true

      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install kubectl
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.VKE_TEST_KUBECONFIG }}
          
      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2
    
      - name: Configure K8s Cluster Access for VKE
        env:
          VKE_TEST_KUBECONFIG: ${{ secrets.VKE_TEST_KUBECONFIG }}
        run: |
          echo $VKE_TEST_KUBECONFIG > ./kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
  
      - name: Create K8s Secrets
        run: |
          if kubectl get configmap hemihatchlings-config --namespace=${{ env.namespace }}; then
            echo "hemihatchlings-config already exists"
          else
            echo "Creating hemihatchlings-config"
            kubectl create configmap hemihatchlings-config \
            --from-literal=PORT=${{ secrets.PORT }} \
            --from-literal=RPC_URL=${{ secrets.RPC_URL }} \
            --namespace=${{ env.namespace }}
          fi
          echo "Checking Dockerhub Secret"
  
    
      - name: Dockerhub Secrets
        run: |
          if kubectl get secret dockerhub-secret --namespace=${{ env.namespace }}; then
            echo "Dockerhub Secret already exists"
          else
            echo "Creating Dockerhub Secret"
            kubectl create secret docker-registry dockerhub-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --docker-email=${{ secrets.DOCKER_EMAIL }} \
            --namespace=${{ env.namespace }}
          fi

      - name: Update Image Tag in Web deployment
        run: |
              kustomize edit set image hemilabs/hemihatchlings-web:latest=${{ env.REPO }}:${{ env.tag }}
              kustomize edit set namespace ${{ env.namespace }}
        working-directory: ./${{ env.INFRA }}

      - name: Checking Kustomize
        run: |
          kustomize build ./${{ env.INFRA }}
          kubectl get all --namespace=${{ env.namespace }}
      
      - name: Deploy to VKE
        run: kubectl apply -k ./${{ env.INFRA }}

      - name: Update Image Tag in API deployment
        run: |
              kustomize edit set image hemilabs/hemihatchlings-web:latest=hemilabs/hemihatchlings-api:${{ env.tag }}
              kustomize edit set namespace ${{ env.namespace }}
        working-directory: ./infrastructure/kustomize_api/base

      - name: Build and Deploy to VKE
        run: |
          echo "TAG_NAME=${{ env.tag }}"
          if [[ "${{ env.tag }}" == "mainnet-v"* ]]; then
            kustomize build ./infrastructure/kustomize_api/overlays/mainnet
            kubectl apply -k ./infrastructure/kustomize_api/overlays/mainnet
          elif [[ "${{ env.tag }}" == "testnet-v"* ]]; then
            kustomize build ./infrastructure/kustomize_api/overlays/testnet
            kubectl apply -k ./infrastructure/kustomize_api/overlays/testnet
          fi
          kubectl get all --namespace=${{ env.namespace }}

        working-directory: .